# Generated by Django 4.0.1 on 2022-05-28 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('My_Application', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datas',
            name='Age',
            field=models.IntegerField(default=''),
        ),
        migrations.AlterField(
            model_name='datas',
            name='Contact',
            field=models.IntegerField(default=''),
        ),
    ]
